### ISSUE TITLE
adding integration / no text

### ISSUE THREAD

**Issue by peters59** [EvanSchalton/tuya-homeassistant-openapi#4] opened 2024-07-21 12:41 UTC
I get only this view when adding the integration
![image](https://github.com/user-attachments/assets/a416c1d1-2ee1-4193-9d45-31f0f913e45c)

**Comment by EvanSchalton** [comment] 2024-07-21 16:47
Hey, this is a duplicate of #2 https://github.com/EvanSchalton/tuya-homeassistant-openapi/issues/2#issuecomment-2062140315

**Closed as completed by EvanSchalton** 2024-07-21 16:47 UTC
